title: Test page Zenodo Auto Searcher
description: "Zenodo Automation is a Python script that connects to the Zenodo API to automate downloading files linked to two search criteria (author and community)."
author: "YairRodz"
  name: "YairRodz"
  email: "someone@somewebsite.somedomain"
  url: "https://yairrodz.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "YairRodz"
year : "2024"
